---
################################################################################################
# Metrics framework configuration
#
# Expose a Prometheus metrics collection endpoint
#
metrics:
  # HTTP hosting server configuration
  service:
    # HTTP server binding port
    appPort: 2001
    # HTTP server binding interface
    listenOn: 0.0.0.0
    # Connection timeout configurations in seconds
    timeoutSecs:
      # Maximum amount of time to wait for the next request when keep-alive is enabled
      # in seconds. If idle timeout is zero, the value of read timeout is used. If both are
      # zero, there is no timeout.
      idle: 300
      # Maximum duration for reading the entire request, including the body in seconds.
      # A zero or negative value means there will be no timeout.
      read: 60
      # Maximum duration before timing out writes of the response in seconds. A zero or
      # negative value means there will be no timeout.
      write: 60
  # Path to host the Prometheus metrics endpoint
  metricsEndpoint: /metrics
  # Max number of metrics requests in parallel to support
  maxRequests: 4
  # Metrics framework features to enable
  features:
    # Whether to enable Golang application metrics
    enableAppMetrics: false

################################################################################################
# Provide custom validation regex patterns
#
# The patterns given here provide validation for the corresponding user inputs.
#
customValidationRegex:
  # User ID input validation
  userID: ^([[:alnum:]]|-|_)+$
  # Username input validation
  username: ^([[:alnum:]]|-|_)+$
  # User permission name input validation
  permission: ^([[:alnum:]]|-|_|:|\.)+$
  # User personal name input validation
  personalName: ^([[:alnum:]]|-)+$
  # User role name input validation
  roleName: ^([[:alnum:]]|-|_)+$

################################################################################################
# User / Role management submodule configuration
#
# This is the administration API / portal for padlock. An admin operates user CRUD, and role
# assignment through this submodule.
#
userManagement:
  # Whether to enable the user / role management submodule
  enabled: true
  ####################################
  # REST API configuration
  #
  apis:
    # REST API end-point configuration
    endPoint:
      # Runtime prefix for API end-point path
      pathPrefix: /
    # REST API request logging configuration
    requestLogging:
      # When logging API requests, do not log these headers
      skipHeaders:
        - WWW-Authenticate
        - Authorization
        - Proxy-Authenticate
        - Proxy-Authorization
  ####################################
  # API HTTP service configuration
  #
  service:
    # HTTP service listening port
    appPort: 3000
    # HTTP service listening interface
    listenOn: 0.0.0.0
    # HTTP service timeout in seconds
    timeoutSecs:
      # Maximum amount of time to wait for the next request when keep-alive is enabled
      # in seconds. If idle timeout is zero, the value of read timeout is used. If both are
      # zero, there is no timeout.
      idle: 300
      # Maximum duration for reading the entire request, including the body in seconds.
      # A zero or negative value means there will be no timeout.
      read: 60
      # Maximum duration before timing out writes of the response in seconds. A zero or
      # negative value means there will be no timeout.
      write: 60
  ####################################
  # User roles used by the management submodule
  #
  # Roles defined here are the available roles for assigning to users. At the start of execution,
  # the management submodule will synchronize available roles defined here with user roles
  # maintained in the user database.
  #
  userRoles:
    # User roles are defined as a dictionary
    #
    # {{ User Role name }}:
    #    permissions:
    #      - {{ permission 1 }}
    #      - {{ permission 2 }}
    #      ...
    #      - {{ permission N }}
    #
    # The role name can be any valid YAML key. However, the system expects that the name are
    # valid (i.e. matches the REGEX pattern defined at customValidationRegex.roleName).
    #
    # The system also expects that the permission names are valid (i.e. match the REGEX pattern
    # defined at customValidationRegex.permission), and the permissions assigned to a role is
    # non-repeating.
    admin:
      permissions:
        - read
        - write
        - modify
        - delete
    reader:
      permissions:
        - read
    writer:
      permissions:
        - write
    user:
      permissions:
        - read
        - write
        - modify

################################################################################################
# User authorization submodule configuration
#
# The authorization submodule accepts verification requests from HTTP proxies to determine
# whether a user is allowed to make a particular REST call. The parameters of the request
# to authorize must be presented via HTTP headers.
#
authorize:
  # Whether to enable the authorization submodule
  enabled: true
  ####################################
  # REST API configuration
  #
  apis:
    # REST API end-point configuration
    endPoint:
      # Runtime prefix for API end-point path
      pathPrefix: /
    # REST API request logging configuration
    requestLogging:
      # When logging API requests, do not log these headers
      skipHeaders:
        - WWW-Authenticate
        - Authorization
        - Proxy-Authenticate
        - Proxy-Authorization
  ####################################
  # API HTTP service configuration
  #
  service:
    # HTTP service listening port
    appPort: 3001
    # HTTP service listening interface
    listenOn: 0.0.0.0
    # HTTP service timeout in seconds
    timeoutSecs:
      # Maximum amount of time to wait for the next request when keep-alive is enabled
      # in seconds. If idle timeout is zero, the value of read timeout is used. If both are
      # zero, there is no timeout.
      idle: 300
      # Maximum duration for reading the entire request, including the body in seconds.
      # A zero or negative value means there will be no timeout.
      read: 60
      # Maximum duration before timing out writes of the response in seconds. A zero or
      # negative value means there will be no timeout.
      write: 60
  ####################################
  # Defines how the submodule should handle an unknown user ID
  #
  forUnknownUser:
    # Whether to automatically record the new user, with no roles assigned to the user.
    autoAdd: true
  ####################################
  # When a HTTP proxy sends a authorization request to padlock, which HTTP headers
  # should the submodule fetch request parameters from.
  #
  requestParamHeaders:
    # Host of the request to authorize
    host: X-Forwarded-Host
    # URI Path of the request to authorize
    path: X-Forwarded-Uri
    # HTTP method of the request to authorize
    method: X-Forwarded-Method
    # Caller user ID of the request to authorize
    userID: X-Caller-UserID
    # Caller username of the request to authorize
    username: X-Caller-Username
    # Caller first name of the request to authorize
    firstName: X-Caller-Firstname
    # Caller last name of the request to authorize
    lastName: X-Caller-Lastname
    # Caller email address of the request to authorize
    email: X-Caller-Email
  ####################################
  # REST request authorization rules
  #
  # The authorization submodules follows the rules defines here when determining whether a
  # REST request is allowed. The submodule checks the:
  #   * Host
  #   * URI Path
  #   * Method
  #
  # to determine which user permissions will allow that REST request to pass. A REST request
  # whose parameter do not match any defined rules are blocked.
  #
  # After determining the permissions list, that is compared against the permissions associated
  # with the user (based on its assigned roles) to see determine to allow the request.
  #
  rules:
    # Authorization rules are grouped by HTTP "host"
    - host: dev-00.testing.org
      # For each host, list out the URI path to check against.
      allowedPaths:
        # Each path is defined by a regex pattern describing it. This is expected to
        # be a PCRE2 complaint regex pattern.
        #
        # NOTE: a wildcard pattern would just be "^.*$"
        - pathPattern: "^/path1$"
          # For each URI path, list out the HTTP methods allow.
          allowedMethods:
            - method: GET
              # For a given HTTP method, which permissions will allow the REST request to pass.
              allowedPermissions:
                - read
            - method: POST
              allowedPermissions:
                - write
        # As multiple path regex patterns may start with the same prefix, the submodule checks
        # each regex pattern from longest to shortest (more specific to less specific).
        - pathPattern: "^/path1/([[:alnum:]]|-)+/?$"
          allowedMethods:
            - method: GET
              allowedPermissions:
                - read
            - method: PUT
              allowedPermissions:
                - modify
            - method: DELETE
              allowedPermissions:
                - delete
        - pathPattern: "^/path2/[[:alpha:]]+/?$"
          allowedMethods:
            # If method is "*", this mean "any HTTP method" is allowed.
            - method: "*"
              allowedPermissions:
                - read
                - write
                - modify
                - delete
    # If host is "*", this mean "any HTTP host" will match.
    - host: "*"
      allowedPaths:
        - pathPattern: "^/path3/?$"
          allowedMethods:
            - method: "*"
              allowedPermissions:
                - read
                - write
                - modify
                - delete
        - pathPattern: "^/path3/([[:alnum:]]|-|_)+/?$"
          allowedMethods:
            - method: GET
              allowedPermissions:
                - read
            - method: PUT
              allowedPermissions:
                - modify

################################################################################################
# User authentication submodule configuration
#
# The authentication submodule accepts verification requests from HTTP proxies to determine
# whether a user can be authenticated.
#
# The submodule authenticates a user via OpenID token validation (the OpenID provider
# configuration is supplied through a separate file), where the token is presented as a
# bearer authorization token.
#
# Upon successful token validation, the submodule will add these additional headers to the
# response. Always present:
#   * User's user ID with the OpenID provider: store as authorize.requestParamHeaders.userID
#
# if available:
#   * User's OpenID username: store as authorize.requestParamHeaders.username
#   * User's first name: store as authorize.requestParamHeaders.firstName
#   * User's last name: store as authorize.requestParamHeaders.lastName
#   * User's email: store as authorize.requestParamHeaders.email
#
# These values are extracted from the token directly, so the user will need to indicate which
# token claims provide which piece of information on the user.
#
# NOTE: the example given here are based on tokens generated by KeyCloak.
#
authenticate:
  # Whether to enable the authentication submodule
  enabled: true
  ####################################
  # REST API configuration
  #
  apis:
    # REST API end-point configuration
    endPoint:
      # Runtime prefix for API end-point path
      pathPrefix: /
    # REST API request logging configuration
    requestLogging:
      # When logging API requests, do not log these headers
      skipHeaders:
        - WWW-Authenticate
        - Authorization
        - Proxy-Authenticate
        - Proxy-Authorization
  ####################################
  # API HTTP service configuration
  #
  service:
    # HTTP service listening port
    appPort: 3002
    # HTTP service listening interface
    listenOn: 0.0.0.0
    # HTTP service timeout in seconds
    timeoutSecs:
      # Maximum amount of time to wait for the next request when keep-alive is enabled
      # in seconds. If idle timeout is zero, the value of read timeout is used. If both are
      # zero, there is no timeout.
      idle: 300
      # Maximum duration for reading the entire request, including the body in seconds.
      # A zero or negative value means there will be no timeout.
      read: 60
      # Maximum duration before timing out writes of the response in seconds. A zero or
      # negative value means there will be no timeout.
      write: 60
  ####################################
  # When a HTTP proxy sends a authentication request to padlock, which HTTP headers
  # should the submodule fetch request parameters from.
  #
  requestParamHeaders:
    # Host of the request to authorize
    host: X-Forwarded-Host
    # URI Path of the request to authorize
    path: X-Forwarded-Uri
    # HTTP method of the request to authorize
    method: X-Forwarded-Method
  ####################################
  # User OpenID token claims of interest
  #
  # If specified, the token must contain an "aud" claim which matches this value.
  #targetAudience:
  # User parameter claims
  targetClaims:
    # User ID claim
    userID: sub
    # Username claim
    username: preferred_username
    # Email claim
    email: email
    # First name claim
    firstName: given_name
    # Last name claim
    lastName: family_name
  ####################################
  # OAuth2 token introspection config
  #
  introspect:
    # Whether introspection is enabled
    enabled: false
    # Interval (sec) to periodically re-introspect cached tokens
    recheckIntervalSec: 300
    # Interval (sec) to periodically clear expired tokens from cache
    cacheCleanIntervalSec: 3600
    # Interval (sec) to periodically purge the token cache
    cachePurgeIntervalSec: 43200
  ####################################
  # Authentication bypass rules
  #
  # This section is OPTIONAL
  #
  # Requests which contain
  # * METHOD
  # * HOST
  # * PATH
  # That match one of the bypass rules will be allowed without authentication checks
  bypass:
    rules:
      # Each rule is defined by a type that indicates which request element this rules applies to
      - type: method
        # If a request property matches one of the possibilities, the request can bypass
        # authentication.
        #
        # Match rules for METHOD, and HOST are case insensitive.
        matches:
          - OPTIONS
          - head
      - type: host
        matches:
          - localhost
          - MY.DEV.ORG
      - type: path
        # PATH matches are parsed as REGEX patterns
        matches:
          - ^/public/path
          - ^/path1$
