---
userManagement:
  userRoles:
    admin:
      permissions:
        - admin
    reader:
      permissions:
        - read
    writer:
      permissions:
        - write
    user:
      permissions:
        - read
        - write
        - modify

authenticate:
  enabled: true
  targetClaims:
    userID: sub
    username: preferred_username
    firstName: given_name
    lastName: family_name
    email: email

authorize:
  forUnknownUser:
    autoAdd: true
  requestParamHeaders:
    host: X-Forwarded-Host
    path: X-Forwarded-Uri
    method: X-Forwarded-Method
    userID: X-Caller-UserID
    username: X-Caller-Username
    firstName: X-Caller-Firstname
    lastName: X-Caller-Lastname
    email: X-Caller-Email
  rules:
    - host: dev-00.testing.org
      allowedPaths:
        - pathPattern: "^/path1$"
          allowedMethods:
            - method: GET
              allowedPermissions:
                - admin
                - read
            - method: POST
              allowedPermissions:
                - admin
                - write
        - pathPattern: "^/path1/([[:alnum:]]|-)+/?$"
          allowedMethods:
            - method: GET
              allowedPermissions:
                - admin
                - read
            - method: PUT
              allowedPermissions:
                - admin
                - modify
            - method: DELETE
              allowedPermissions:
                - admin
                - modify
        - pathPattern: "^/path2/[[:alpha:]]+/?$"
          allowedMethods:
            - method: "*"
              allowedPermissions:
                - admin
    - host: "*"
      allowedPaths:
        - pathPattern: "^/path3/?$"
          allowedMethods:
            - method: "*"
              allowedPermissions:
                - admin
        - pathPattern: "^/path3/([[:alnum:]]|-|_)+/?$"
          allowedMethods:
            - method: GET
              allowedPermissions:
                - admin
                - read
            - method: PUT
              allowedPermissions:
                - admin
                - modify
