services:
  padlock-dev-db:
    container_name: padlock-dev-db
    hostname: "postgres"
    image: "postgres:15"
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - padlock-dev

networks:
  padlock-dev:
