name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  revive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Revive
        run: |
          docker run --rm -v "$(pwd)":/work -w /work \
            ghcr.io/mgechev/revive:v1.13.0 \
            -config revive.toml -formatter stylish ./...

  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4
          args: --timeout 3m0s

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Build
        run: go build -v -o padlock .

      - name: Test
        run: go test --count 1 -timeout 30s -short ./...
