---
name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPO: alwitt/padlock
      IMAGE_TAG: "0.4.0"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub for only main branch
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          push: ${{ github.ref == 'refs/heads/main' }}
